.PHONY: start_server stop_server debug_server_start db_stop db_start

start_server:
	bash ./admin/runner.sh start_server

stop_server:
	bash ./admin/runner.sh stop_server

debug_server_start:
	bash ./admin/runner.sh debug_server_start

db_stop:
	bash ./admin/runner.sh db_stop

db_start:
	bash ./admin/runner.sh db_start
